[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[build]
  command = 'pnpm build'
  publish = 'build/client/'

[build.environment]
  NODE_VERSION="20"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"